### ISSUE TITLE
Clicking the GetTogather logo after logging our returns user to logged-in homepage

### ISSUE THREAD

**Issue by brown-jh** [jaredmario108/COP4331LargeProject#29]
Probably shouldn't do that

**Comment by jaydensipe** [comment]
I think this is due to the JWT not expiring, any potential workarounds?

**Comment by AlyxReckahn** [comment]
@jaydensipe @brown-jh Either it should erase the JWT on logout (I could swear the MERN demo did that, and since the LAMP demo could, this one probably should do the same) and then check for a valid token before redirecting, or have it check the current URL and refuse to redirect if on one of the non-logged-in pages.

**Comment by jaydensipe** [comment]
"Fixed" in 303c6fa0b3aeebceb21ae8a1c73f11d573f8b047, just made it so the user can't click to goto home on certain pages.
